---
title: "eda"
author: "Jiayi Yang"
date: "2022-10-06"
output: github_document
---
```{r}
library(tidyverse)
library(lubridate)
```

```{r}
weather_df =  
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>%
  select(name, id, everything())
```

## summarize()

let's group and summarize

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(
    n_obs = n()
  )
```

alternative to group_by

```{r}
weather_df %>% 
  count(name, month)
```

don't use `table()`!

```{r}
weather_df %>% 
  pull(month) %>% 
  table
```

we can have multiple summaries
```{r}
weather_df %>% 
  group_by(month) %>% 
  summarize(
    n_obs = n(),
    n_dist = n_distinct(date)
  )
```

## briefly 2*2 table
```{r}
weather_df %>% 
  mutate(
    cold = case_when(
      tmax <  5 ~ "cold",
      tmax >= 5 ~ "not_cold",
      TRUE      ~ ""
  )) %>% 
  filter(name != "Waikiki_HA") %>% 
  janitor::tabyl(name, cold)
```

## General summaries
```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(
    n_obs = n(),
    mean_tmax = mean(tmax, na.rm = TRUE),
    sd_prcp = sd(prcp),
    median_tmax = median(tmax, na.rm = FALSE)
  )
```
```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize( mean_tmax = mean(tmax),
    median_tmax = median(tmax))
```

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(
    mean_tmax = mean (tmax, na.rm = TRUE)
  ) %>% 
  ggplot(aes(x = month, y = mean_tmax, color = name))+
  geom_point()+
  geom_path()

```
knitr kable function

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE)
  ) %>% 
  pivot_wider(
    names_from = name,
    values_from = mean_tmax) %>% 
  knitr::kable(digit = 1)
```

Group by mutate
```{r}
weather_df %>%
  group_by(name) %>%
  mutate(
    mean_tmax = mean(tmax, na.rm = TRUE),
    centered_tmax = tmax - mean_tmax) %>% 
  ggplot(aes(x = date, y = centered_tmax, color = name)) + 
    geom_point() 
```

Window function: lagged observation
```{r}
weather_df %>% 
  group_by(name) %>% 
  mutate(
    yesterday_tmax = lag(tmax),
    tmax_change = tmax - yesterday_tmax
  ) %>% 
  summarize(
    sd_tmax_change = sd(tmax_change, na.rm = TRUE)
  )
```

Window function: 
```{r}
weather_df %>%  
  group_by(name, month) %>% 
  mutate(
    tmax_rank = min_rank(tmax)
  ) %>% 
  filter(tmax_rank < 4) %>% 
  arrange(name, month, tmax_rank)
```

